repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
        name: Prevent errors on case-insensitive filesystems
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Ensure file ends with one newline


  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-install
        name: Install packages from poetry.lock
      - id: poetry-check
        name: Validate poetry config

      - id: poetry-lock
        name: Verify poetry.lock file
        args:
          - --no-update

      - id: poetry-export
        name: Export dependancies
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: false

      - id: poetry-export
        name: Export dev dependancies
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
        verbose: false


  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        name: Format python files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        name: Lint python code
        args:
          - --fix
