repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json

      - id: check-toml

      - id: check-yaml

      - id: check-case-conflict
        name: Prevent errors on case-insensitive filesystems

      - id: trailing-whitespace
        name: Trim trailing whitespace

      - id: end-of-file-fixer
        name: Ensure file ends with one newline

      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
        name: Format markdown files

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.2
    hooks:
      - id: uv-export
        name: Export dependencies
        always_run: true
        args:
          - --output-file=requirements.txt
          - --no-dev
          - --quiet
        files: ^pyproject\.toml$

      - id: uv-export
        name: Export dev dependencies
        always_run: true
        args:
          - --only-dev
          - --output-file=requirements-dev.txt
          - --quiet
        files: ^pyproject\.toml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        name: Lint python code
        args:
          - --fix

      - id: ruff-format
        name: Format code & sort imports
