repos:
  - hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0

  - hooks:
      - id: poetry-check
      - args:
          - --no-update
        id: poetry-lock
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
      - id: poetry-install
    repo: https://github.com/python-poetry/poetry
    rev: 1.7.0

  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.1.1

  - hooks:
      - id: markdownlint
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0

  - hooks:
      - args:
          - --fix
        id: ruff
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15