name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      message1:
        description: 'Parameter message'
        required: true
        default: 'no message'
      tag1:
        description: 'Test scenario tags'
        required: false

env:
  GH_USER: iHarshad
  GH_REPO: iharshad.github.io
  GH_PAT: ${{ secrets.GH_DEPLOY_KEY }}
  GH_WORKFLOW: gh-pages.yml



defaults:
  run:
    shell: bash

# Sets permissions for the GITHUB_TOKEN to write to repository
permissions:
  contents: write     # create a release
  deployments: write  # permits an action to create a new deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Simple echo
        run: |
          echo -e $GITHUB_TOKEN;
          echo -e $GITHUB_WORKFLOW;
          echo -e $GITHUB_ACTION;
          echo -e $GITHUB_EVENT_NAME;
          echo -e $GH_PAT;

      - run: |
          git log --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"
          echo "Message: ${{ github.event.inputs.message1 }}"
          echo "Tags: ${{ github.event.inputs.tag1 }}"

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python3 main.py

