name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      message1:
        description: 'Parameter message'
        required: true
        default: 'no message'
      tag1:
        description: 'Test scenario tags'
        required: false

# env:
#   GH_USER: iHarshad
#   GH_REPO: iharshad.github.io
#   GH_PAT: ${{ secrets.GH_DEPLOY_KEY }}
#   GH_WORKFLOW: gh-pages.yml



defaults:
  run:
    shell: bash

# Sets permissions for the GITHUB_TOKEN to write to repository
permissions:
  contents: write     # create a release
  deployments: write  # permits an action to create a new deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Checkout other repo
        uses: actions/checkout@v4 # checkout the repository content to github runner
        with:
          repository: iHarshad/other-repo
          token: ${{ secrets.GH_PAT }}
          ref: other  # checkout 'other' branch
          path: other-repo
          fetch-depth: 1

      - name: Simple echo
        run: |
          echo -e $GITHUB_TOKEN;
          echo -e $GITHUB_WORKFLOW;
          echo -e $GITHUB_ACTION;
          echo -e $GITHUB_EVENT_NAME;
          echo -e $GH_PAT;
          ls -alh;

      - name: Hygiene logging
        run: |
          git log --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A"
          echo "Message: ${{ github.event.inputs.message1 }}"
          echo "Tags: ${{ github.event.inputs.tag1 }}"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: Install python dependancy packages
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt

      - name: Execute python code
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          MY_REPO: ${{ secrets.MY_REPO}}
        run: python3 main.py
