name: Post Handler Action

on:
  repository_dispatch:
    types: [post-event]

jobs:
  process-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MY_PRIVATE_REPO }}
          token: ${{ secrets.GH_PAT }}
          path: private-repo

      # - name: Set up payload data
      #   run: |
      #     echo '${{ toJSON(github.event.client_payload) }}' > payload.json
      #     cat payload.json

      # - name: Reset database
      #   run: |
      #     rm -f private-repo/*.db

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.12"

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Debug
        run: |
          ls -alh --color=auto
          date +"%A %d %b %Y %Z"
          echo $GITHUB_EVENT_PATH

      - name: Run script from private repository with payload data
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          ENCODED_KEY: ${{ secrets.ENCODED_KEY }}
        run: |
          cd private-repo
          uv run --script insert.py

      # - name: Commit and push changes
      #   run: |
      #     cd private-repo
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git add .
      #     # git commit -m "Update from GitHub Action with payload: $(cat ../payload.json | jq -r '.message')"
      #     git commit -m "Update from GitHub Action"
      #     git push

      - name: Cleanup
        run: echo "Action completed successfully"
